import "./globals.css";
import { Inter, Unbounded } from "next/font/google";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  display: "swap",
});
const unbound = Unbounded({
  subsets: ["latin"],
  variable: "--unbound",
  display: "swap",
});

export const metadata = {
  title: "Geeksvisor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${unbound.variable}`}>
        <ToastContainer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
