import { Inter, Unbounded } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  display: "swap",
});
const unbound = Unbounded({
  subsets: ["latin"],
  variable: "--unbound",
  display: "swap",
});

export const metadata = {
  title: "Geeksvisor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(inter.variable, unbound.variable)}>{children}</body>
    </html>
  );
}
